### ISSUE TITLE
[Question] why use traefik rather than an OS-packaged proxy like nginx

### ISSUE THREAD

**Issue by mangecoeur** [jupyterhub/the-littlest-jupyterhub#190]
As said title, more a question - I was wondering why you chose traefik as a reverse proxy rather than Nginx. I would see the advantage of Nginx being that its ultra-mature and that it's in the package repos for the target OSes, meaning that it's guaranteed to get stable, non-breaking security updates directly from the OS repos. On the other hand I had never heard of traefik before so I don't know what it's advantages are.

I've ended up using Nginx for this reason, my Ubuntu server is set with auto-update and kernel livepatch and I get a notification when a server restart is needed for certain updates - since our system is exposed to the web it adds peace of mind! But am I missing something by not using traefik?

**Comment by mangecoeur** [comment]
Thanks that's really helpful!

**Comment by yuvipanda** [comment]
Hope @minrk's comment answered all your questions, @mangecoeur!

**Comment by mangecoeur** [comment]
Yup! 😊

Sent from Mail for Windows 10

**Comment by mikanyman** [comment]
tljh installed nicely. I have a subdomain dedicated for tljh, but otherwise the services on the domain run under nginx. When I call the subdomain from a browser I get the nginx welcome page as response. "configure tljh to run on localhost only, and do ssl termination, proxying with nginx" seems to be the solution, but I don't know how to do that. I would really appreciate any help.
