### ISSUE TITLE
Make it clearer that you always need a domain name for HTTPS

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#217]
HTTPS generally does not work with IP addresses - you need a domain name. Make sure your HTTPS docs make this clear. 

From conversation with @mdogy

**Comment by fm75** [comment]
@yuvipanda 
It should be easy enough to explain that you need a domain name that can be reached by DNS. Is it sufficient to add this to docs/howto/admin/https.rst, or does it also need instructions on setting up DNS?  

How to set up DNS will be different if access is via the internet, versus doing it on a private network.

Should I not pick this up myself because of the `good first issue` label?

**Comment by yuvipanda** [comment]
Apologies for  not getting back to this issue for so long! I have documented this as part of #328, hopefully that's clear enough.

**Comment by fm75** [comment]
#328 looks good to me.

**Comment by yuvipanda** [comment]
Thanks for taking a look, @fm75
