### ISSUE TITLE
Issue with deleting users

### ISSUE THREAD

**Issue by rraghav13** [jupyterhub/the-littlest-jupyterhub#231]
I switched my authentication method and logged in a user. Due to some syntax issue(backslashes involved in username), the UserCreatingSpawner failed to create the user account and folder in the host `subprocess.CalledProcessError: Command '['useradd', '--create-home', 'jupyter-lastname\\, firstname-c30e6']' returned non-zero exit status 3.`. Now, I want to just delete the user from jupyterhub. When I try to delete it from the admin page, I get a 500 error. Logs mention a `KeyError` because I guess it is not able to find it in the passwords.dbm file. How do I solve this issue?

**Comment by choldgraf** [comment]
hmmm, I believe in some other issues we've also mentioned telling people how to manually delete things like user data etc. We should flag this issue when somebody implements that information, I agree it'd be useful!

**Comment by lachlancampbell** [comment]
I'm also unable to delete a number of users, API returns "API request failed (500): Internal Server Error". I have manually removed the unix users and home directories, but the usernames still appear on the admin page.

**Comment by hoenie-ams** [comment]
Ran into the same issue with the NativeAuthenticator while using e-mail addresses as usernames.

**Comment by GeorgianaElena** [comment]
Closing this as the issue seems to be solved for FirstUseAuthenticator. @hoenie-ams, if you still have issues deleting users when using NativeAuthenticator, please open an issue on the authenticator's [GitHub repo](https://github.com/jupyterhub/nativeauthenticator) or ask on the [Jupyter Discourse forum](https://discourse.jupyter.org/). Thanks :sunflower:
