### ISSUE TITLE
White list of GitHub Authenticator

### ISSUE THREAD

**Issue by ypff** [jupyterhub/the-littlest-jupyterhub#269]
Hello

Does GitHub Authenticator support organization white list? I set up org_whitelist, but it doesn't work.
![snppyvqaaynhra7oscselaw](https://user-images.githubusercontent.com/42979997/51994351-940efc00-247e-11e9-8828-453dd522ab10.png)

**Comment by leportella** [comment]
Not sure, but this seems like a question that would be more suitable [on the repository of the Authenticator](https://github.com/jupyterhub/oauthenticator/issues)

**Comment by yuvipanda** [comment]
@ypff from looking at the oauthenticator repo (https://github.com/jupyterhub/oauthenticator) I believe it will work if you use `github_organization_whitelist` as the key, and make the value a list instead of string.

If that doesn't work for you, as @leportella says, please open an issue in the OAuthenticator repo or Discourse. Thank you!
