### ISSUE TITLE
Upgrade conda & hide the 'new version' nag during install

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#332]
It's confusing a lot of people, and probably hiding other real errors. See https://github.com/jupyterhub/the-littlest-jupyterhub/issues/281 for example.

**Comment by wqh17101** [comment]
i find that you check conda and traefik version which is a constant why not put the install script/package in the repo,and install from it . @yuvipanda

**Comment by choldgraf** [comment]
Just a note that @poldrack ran into some issues with this today in a class that he was teaching. It sounds like the version of conda is out-of-date enough that it is starting to create bugs for users (I think there was an error where conda couldn't install anything because some kind of outdated version mismatch happened)

perhaps this is something @GeorgianaElena could help out with?
