### ISSUE TITLE
Issues connecting to kernel behind corporate firewall

### ISSUE THREAD

**Issue by nick-gibb** [jupyterhub/the-littlest-jupyterhub#469]
I followed the instructions to install TLJH on AWS EC2. 

Works great... Except not when I'm on my work Internet. The Python kernel fails to connect. This is the error in the JavaScript console:

```
kernel.js:461 WebSocket connection to [AWS url omitted] failed: Error during WebSocket handshake: Unexpected response code: 504
```

Wondering if there's a way to resolve this without bugging the security team at my workplace? Maybe if I implement HTTPS? Currently I'm just using basic HTTP.

Thanks.

Edit: I guess this issue is the same as #301

**Comment by nick-gibb** [comment]
Our IT team fixed it.

**Comment by MartijnZ** [comment]
Hi Nick,

I run into a similar issue at my corporate network: outside the firewall it works fine, inside not.
Do you know what the IT department did to fix this issue?

Cheers,

Martijn

**Comment by MartijnZ** [comment]
Our IT-guys were quick in sorting it out: 'WebSocket' needed to be added to the firewall exceptions

**Comment by mhwasil** [comment]
I had the same problem when running jupyterhub behind firewall, it works fine without firewall.
could you @MartijnZ and @nick-gibb  share your solution to fix this?
how can I add the `WebSocket` to the firewall?

**Comment by MartijnZ** [comment]
Hi @mhwasil,

I found out what exceptions to add to the firewall in collaboration with my network-administrator. By monitoring the firewall while trying to accessing Jupyterhub from behind the Firewall, we were able to figure out what exceptions to add to make it work. In our case it was only 'WebSocket'

I hope this helps.

Cheers,

Martijn

**Comment by mhwasil** [comment]
> Hi @mhwasil,
> 
> I found out what exceptions to add to the firewall in collaboration with my network-administrator. By monitoring the firewall while trying to accessing Jupyterhub from behind the Firewall, we were able to figure out what exceptions to add to make it work. In our case it was only 'WebSocket'
> 
> I hope this helps.
> 
> Cheers,
> 
> Martijn

In my case, I am using [lernstick](https://github.com/imedias/lernstickAdvanced) with [this firewall configuration](https://github.com/imedias/lernstick-firewall) and it uses [squid](https://github.com/imedias/lernstick-firewall) to redirect the traffic so that the users are not allowed to connect to other url other than the specified ones. I have modified this firewall so that it can connect to another proxy server, which runs on different pc with nginx, and routes the traffic to our jupyterhub server.

But I did not get any luck, here is the error from the console
```
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:48142 WebSocket connection to 'ws://192.168.2.102/user/test-user/api/kernels/fffca9b4-aa24-40e0-bca3-f4afc4a75e89/channels?session_id=ec3cf46e45ac4694a65024ce2303a886' failed: WebSocket opening handshake timed out
```
I have tried both http and https, but the problem persists when I enable the firewall.
