### ISSUE TITLE
Using LocalAuthenticator with TLJupyterHub

### ISSUE THREAD

**Issue by ReubenTheDS** [jupyterhub/the-littlest-jupyterhub#638]
Team, first off, great project!
Is there a way to get LocalAuthenticator to work with The Littlest Jupyter Hub, so that (Ubuntu) users can log in automatically, instead of an admin creating user-accounts? I see it's not included as part of the [authenticators shipped with TLJH](https://tljh.jupyter.org/en/latest/topic/authenticator-configuration.html). I still tried the following:
```
sudo tljh-config set auth.type localauthenticator.LocalAuthenticator
sudo tljh-config reload
```
but it just hangs. Is there a link/guide on how to get this working?

**Comment by GeorgianaElena** [comment]
Hey @ReubenTheDS :wave: TLJH should work with `LocalAutheticantor`, without installing any extra pkg.

The `tljh-config` command that activates this authenticator is:
```
sudo tljh-config set auth.type jupyterhub.auth.LocalAuthenticator
sudo tljh-config reload
```
(The `LocalAuthenticator` is part of the [`jupyterhub` package](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L727))

Hope this helps :smiley_cat: . If you have any other question or config issue, please post on the Jupyter Discourse forum (https://discourse.jupyter.org/). Thank you!

**Comment by ReubenTheDS** [comment]
> Hey @ReubenTheDS 👋 TLJH should work with `LocalAutheticantor`, without installing any extra pkg.
> 
> The `tljh-config` command that activates this authenticator is:
> 
> ```
> sudo tljh-config set auth.type jupyterhub.auth.LocalAuthenticator
> sudo tljh-config reload
> ```
> 
> (The `LocalAuthenticator` is part of the [`jupyterhub` package](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L727))
> 
> Hope this helps 😺 . If you have any other question or config issue, please post on the Jupyter Discourse forum (https://discourse.jupyter.org/). Thank you!

Thank you for the clarification. I'll surely try this.
My two cents:
In the doc for Authentication at  https://tljh.jupyter.org/en/latest/topic/authenticator-configuration.html  there is  no mention of inbuilt support for Local Authentication in the "shipped" list.

**Comment by GeorgianaElena** [comment]
The authenticator list at https://tljh.jupyter.org/en/latest/topic/authenticator-configuration.html, has the authenticators that are installed by default when installing TLJH. These are part of their own packages and are installed by TLJH here: https://github.com/jupyterhub/the-littlest-jupyterhub/blob/28e7cfde2a00baaa51c971ce237c73e21afe9c1d/tljh/installer.py#L225-L233

But there are three more authenticators that are part of the jupyterhub package itself. These are the authenticators ([DummyAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L1115), [LocalAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L727) and [PAMAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L905)) in this file: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py.

I agree, that having a note about this in the docs would be a great addition. Also, the `DummyAuthenticator` used to be part of its own package, but has since been added to the `jupyterhub` package itself. The TLJH docs haven't been updated with this change though :(

Would like to open up a PR to help improve the docs with this info? It would be amazing :heart: I will open up an issue about this. Thanks a lot @ReubenTheDS!

**Comment by ReubenTheDS** [comment]
> The authenticator list at https://tljh.jupyter.org/en/latest/topic/authenticator-configuration.html, has the authenticators that are installed by default when installing TLJH. These are part of their own packages and are installed by TLJH here:
> 
> https://github.com/jupyterhub/the-littlest-jupyterhub/blob/28e7cfde2a00baaa51c971ce237c73e21afe9c1d/tljh/installer.py#L225-L233
> 
> But there are three more authenticators that are part of the jupyterhub package itself. These are the authenticators ([DummyAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L1115), [LocalAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L727) and [PAMAuthenticator](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L905)) in this file: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py.
> 
> I agree, that having a note about this in the docs would be a great addition. Also, the `DummyAuthenticator` used to be part of its own package, but has since been added to the `jupyterhub` package itself. The TLJH docs haven't been updated with this change though :(
> 
> Would like to open up a PR to help improve the docs with this info? It would be amazing ❤️ I will open up an issue about this. Thanks a lot @ReubenTheDS!

[GE] Would like to open up a PR to help improve the docs with this info?
Me: I have very little knowledge of GitHub and source code versioning in general, let alone creating a PR and knowing what to do with it once created. Sorry :-)

**Comment by GeorgianaElena** [comment]
No worries, @ReubenTheDS! Having spotted this missing info in the docs, is already a great contribution to this project. Thank you :heart:
