### ISSUE TITLE
Setting template_paths doesn't have any effect

### ISSUE THREAD

**Issue by ibayer** [jupyterhub/the-littlest-jupyterhub#669]
### Bug description

Jupyterhubs visual appearance can be customized using templates.

- https://jupyterhub.readthedocs.io/en/stable/reference/templates.html#extending-templates
- https://github.com/jupyterhub/jupyterhub/issues/1385

This should be possible with the following config

```
cat /opt/tljh/config/jupyterhub_config.d/custom.py 
c.JupyterHub.template_paths = ['/opt/tljh/config/jupyterhub_config.d']
```
as described in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/434#issuecomment-574159678

I also have the following file:
 
```
cat /opt/tljh/config/jupyterhub_config.d/login.html 
{% extends "templates/page.html" %}
{% set announcement = 'some  message' %}
```

However making this changes doesn't have any effect.

#### Expected behaviour

Using templates should have the same effect as

```
cat config/jupyterhub_config.d/custom.py 
c.JupyterHub.template_vars = {'announcement': 'some  message'}
```
which shows a message on the login page.

#### Actual behaviour

Adding template files to `/opt/tljh/config/jupyterhub_config.d/login.html ` has no visible effect.

### How to reproduce

see above

### Your personal set up

I'm using the-littlest-jupyterhub.

 - OS: ubuntu 18.04

pip3 freeze
<details>

```
 pip3 freeze
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==20.4
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
ec2-hibinit-agent==1.0.0
entrypoints==0.3
hibagent==1.0.1
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
MarkupSafe==1.1.0
more-itertools==4.2.0
netifaces==0.10.4
oauthlib==3.1.0
pexpect==4.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.4
python-debian===0.1.36ubuntu1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.0
ssh-import-id==5.10
systemd-python==234
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
zipp==1.0.0
zope.interface==4.7.1

```

</details>

**Comment by ibayer** [comment]
@GeorgianaElena I tried to follow your recommended steps https://github.com/jupyterhub/the-littlest-jupyterhub/issues/434#issuecomment-574159678 could you give me some advice how to trace this issue?

related issues:

- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/434
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/653

**Comment by GeorgianaElena** [comment]
Hey @ibayer! :wave: :sunflower: 

I'm assuming that since you're extending `page.html`, then you want the announcement message to be present on all pages, right? In this case, then you should name the custom template `page.html` instead of `login.html`. The reason is that `page.html` is extended by almost all the default JupyterHub templates, so the change will get in every template, including `login.html`

In the current state, with `login.html` being 
```
{% extends "templates/page.html" %}
{% set announcement = 'some  message' %}
```
You'll overwrite everything that's in the [login.html default template](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/login.html) and if you logout, then you'll probably won't be able to login again.

So, I believe the only change needed is to rename `/opt/tljh/config/jupyterhub_config.d/login.html` into `/opt/tljh/config/jupyterhub_config.d/page.html`. This is how it looks for me with this:

Main home page:
![page-html1](https://user-images.githubusercontent.com/7579677/112439161-73d2e300-8d51-11eb-9d62-fca8419670ad.png)

Login page:
![page-html2](https://user-images.githubusercontent.com/7579677/112439169-759ca680-8d51-11eb-833f-051c39d6cd1f.png)

I'll label this issue as a `support` question and the issue will probably get closed by the bot (we are trying to keep only feature requests and bug reports on GitHub and all the other conversations on our community forum https://discourse.jupyter.org/ ). But please let me know if it worked and if you have any other support/configuration question, please feel free to post on the forum! Thank you :heart:
