### ISSUE TITLE
Remove support for Ubuntu 18.04 (deprecated environment)

### ISSUE THREAD

**Issue by pnasrat** [jupyterhub/the-littlest-jupyterhub#852]
Got below 18.04 brownout message in the test runs for a PR. As 18.04 is EOL (with only ESM support available). 

Support for 18.04 should be removed from tljh.

This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002

**Comment by manics** [comment]
I agree. We should tag a proper release (0.2.0) with the existing supported versions first so that people can easily stay on the old version:
- https://github.com/jupyterhub/the-littlest-jupyterhub/pull/838
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/724

Once that's done we can upgrade everything, drop unsupported operating systems, and release 1.0.0 :smiley:
